kingkong/kingkong/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    # add route from todo Application
    path('monyet/', include('monyet.urls'))
]

kingkong/monyet/urls.py
from django.contrib import admin 
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings 

# import View dari todo Application
from .views import index_view, say_view, create_view, update_view, delete_view

app_name = 'monyet'
urlpatterns = [
    # url untuk halaman daftar task
    path('', index_view, name='index'),
    # url untuk halaman detail task
    path('<int:task_id>', say_view, name='say'),
    # url untuk halaman tambah task
    path('create', create_view, name='create'),
    # url untuk halaman ubah task
    path('update/<int:task_id>', update_view, name='update'),
    # url untuk menghapus task
    path('delete/<int:task_id>', delete_view, name='delete'),
]

kingkong/monyet/models.py
from django.utils.translation import gettext_lazy as _
from django.db import models


class Task(models.Model):
    # define status choices/options
    class TaskStatus(models.TextChoices):
        TODO = 'monyet', _('Monyet')
        IN_PROGRESS = 'in_progress', _('In Progress')
        CLOSED = 'closed', _('Closed')
    
    # define columns
    nama = models.CharField(max_length=100)
    keluarga = models.TextField()
    status = models.CharField(
        max_length=20,
        choices=TaskStatus.choices,
        default=TaskStatus.TODO
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # define table name
        db_table = 'tasks'

kingkong/monyet/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

# import class Task dari file todo/models.py
from .models import Task


# membuat class TaskForm untuk membuat task
class TaskForm(ModelForm):
    class Meta:
        # merelasikan form dengan model
        model = Task
        # mengeset field apa saja yang akan ditampilkan pada form
        fields = ('nama', 'keluarga', 'status')
        # mengatur teks label untuk setiap field
        labels = {
            'nama': _('Nama'),
            'keluarga': _('Keluarga'),
            'status': _('Status')
        }
        # mengatur teks pesan error untuk setiap validasi fieldnya
        error_messages = {
            'nama': {
                'required': _("Nama harus diisi."),
            },
            'keluarga': {
                'required': _("Keluarga harus diisi."),
            },
        }

kingkong/monyet/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import redirect, render
from django.http import Http404
from django.contrib import messages

# import class Task dari file todo/models.py
from .models import Task
# import class TaskForm dari file todo/forms.py
from .forms import TaskForm


# Membuat View untuk halaman daftar task
def index_view(request):
    # Mengambil semua data task
    tasks = Task.objects.all()
    context = {
        'tasks': tasks
    }
    # parsing data task ke template todo/index.html dan merender nya
    return render(request, 'hawkish/index.html', context)


# Membuat View untuk halaman detail task
def say_view(request, task_id):
    # Mengambil data task berdasarkan task ID
    try:
        task = Task.objects.get(pk=task_id)
        context = {
            'task': task
        }
    except Task.DoesNotExist:
        # Jika data task tidak ditemukan,
        # maka akan di redirect ke halaman 404 (Page not found).
        raise Http404("Task tidak ditemukan.")
    # parsing data task ke template todo/detail.html dan merendernya
    return render(request, 'hawkish/say.html', context)


# Membuat View untuk halaman form tambah task
def create_view(request):
    # Mengecek method pada request
    # Jika method-nya adalah POST, maka akan dijalankan
    # proses validasi dan penyimpanan data
    if request.method == 'POST':
        # membuat objek dari class TaskForm
        form = TaskForm(request.POST)
        # Mengecek validasi form
        if form.is_valid():
            # Membuat Task baru dengan data yang disubmit
            new_task = TaskForm(request.POST)
            # Simpan data ke dalam table tasks
            new_task.save()
            # mengeset pesan sukses dan redirect ke halaman daftar task
            messages.success(request, 'Sukses Menambah Task baru.')
            return redirect('monyet:index')
    # Jika method-nya bukan POST
    else:
        # membuat objek dari class TaskForm
        form = TaskForm()
    # merender template form dengan memparsing data form
    return render(request, 'hawkish/form.html', {'form': form})

def update_view(request, task_id):
    try:
        # mengambil data task yang akan diubah berdasarkan task id
        task = Task.objects.get(pk=task_id)
    except Task.DoesNotExist:
        # Jika data task tidak ditemukan,
        # maka akan di redirect ke halaman 404 (Page not found).
        raise Http404("Task tidak ditemukan.")
    # Mengecek method pada request
    # Jika method-nya adalah POST, maka akan dijalankan
    # proses validasi dan penyimpanan data
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            # Simpan perubahan data ke dalam table tasks
            form.save()
            # mengeset pesan sukses dan redirect ke halaman daftar task
            messages.success(request, 'Sukses Mengubah Task.')
            return redirect('monyet:index')
    # Jika method-nya bukan POST
    else:
        # membuat objek dari class TaskForm
        form = TaskForm(instance=task)
    # merender template form dengan memparsing data form
    return render(request, 'hawkish/form.html', {'form': form})

def delete_view(request, task_id):
    try:
        # mengambil data task yang akan dihapus berdasarkan task id
        task = Task.objects.get(pk=task_id)
        # menghapus data dari table tasks
        task.delete()
        # mengeset pesan sukses dan redirect ke halaman daftar task
        messages.success(request, 'Sukses Menghapus Task.')
        return redirect('monyet:index')
    except Task.DoesNotExist:
        # Jika data task tidak ditemukan,
        # maka akan di redirect ke halaman 404 (Page not found).
        raise Http404("Task tidak ditemukan.")

kingkong/monyet/templates/hawkish/form.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Ubah</title>

    <style>
      body {
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Task Form</h1>

      <div>
        <a href="{% url 'monyet:index' %}" class="btn btn-success">Back to List</a>
      </div>

      <br>

      <div>
        <!-- meload package untuk merender form field -->
        {% load widget_tweaks %}

        <form method="post" novalidate>
          <!-- menambahkan csrf field untuk keamanan form -->
          {% csrf_token %}

          <!-- merender semua field form dari objek TaskForm -->
          {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              {% for error in form.non_field_errors %}
                {{ error }}
              {% endfor %}
            </div>
          {% endif %}

          {% for field in form.visible_fields %}
            <div class="form-group">
              {{ field.label_tag }}

              {% if form.is_bound %}
                {% if field.errors %}
                  {% render_field field class="form-control is-invalid" %}
                  {% for error in field.errors %}
                    <div class="invalid-feedback">
                      {{ error }}
                    </div>
                  {% endfor %}
                {% else %}
                  {% render_field field class="form-control is-valid" %}
                {% endif %}
              {% else %}
                {% render_field field class="form-control" %}
              {% endif %}

              {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
              {% endif %}
            </div>
          {% endfor %}

          <div>
            {% if messages %}
            
                  {% for message in messages %}
                  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                    </button>
                      {{ message | safe }}
                  </div>
                  {% endfor %}
            
            {% endif %}
            </div>
            
            <!-- tombol untuk ke halaman tambah task -->
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
  </div>
 
  </body>
</html>

kingkong/monyet/templates/hawkish/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css"
    />
    <title>Mamalia Primate</title>
    <link rel="stylesheet" href="{% static '/css/style.css' %}" />
   
  </head>
  <body>

    <div class="rumput">
      <!-- <img src="{% static 'images/rumput.svg'%}" alt="rumput" /> -->
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <a class="navbar-brand" href="#"
            ><img
              src="{% static 'images/navbar.svg'%}"
              class="float-start"
              alt="navbar"
              width="100"
              height="100"
            />
              <h1 class="text-success">Daftar Keluarga Hewan</h1>
              <h3 class="text-secondary">Mamalia & Ovipar</h3>
            </div>
          </a>
      </nav>

      <div class="container">
        <div class="container pt-5">
          <!-- blok untuk menampilkan notifikasi pesan sukses -->
          <div>
            {% if messages %} {% for message in messages %}
            <div
              class="alert alert-{{ message.tags }} alert-dismissible fade show"
              role="alert"
            >
              <button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
              {{ message | safe }}
            </div>
            {% endfor %} {% endif %}
          </div>

          <!-- tombol untuk ke halaman tambah task -->

          <br/>
          <table
            class="table table-bordered table-striped table-info table-hover table-responsive"
          >
            <thead>
                <tr class="table-dark">
                <th width="5%">No</th>
                <th width="20%">Nama</th>
                <th width="45%">Keluarga</th>
                <th width="5%">Keadaan</th>
                <th width="25%">Aksi</th>
              </tr>
            </thead>
            <tbody>
              <!-- daftar task-->
              {% if tasks %} {% for task in tasks %}
              <tr>
                <td>{{ task.id }}</td>
                <td>{{ task.nama }}</td>
                <td>{{ task.keluarga }}</td>
                <td>{{ task.status }}</td>

                <td class="flex">
                  <a href="{% url 'monyet:say' task.id %}" class="btn btn-sm"
                    ><div class="four">
                      <img
                        src="{% static '/images/detail.svg'%}"
                        width="100px"
                        height="100px"
                        alt="detail"
                      /></div
                  ></a>
                  <a href="{% url 'monyet:update' task.id %}" class="btn btn-sm"
                    ><div class="tree">
                      <img
                        src="{% static 'images/ubah.svg'%}"
                        height="100px"
                        width="100px"
                        alt="ubah"
                      /></div
                  ></a>
                  <a
                    href="{% url 'monyet:delete' task.id %}"
                    class="btn btn-sm"
                    onclick="return confirm('Apakah yakin akan menghapus task ini?')"
                    ><div class="two">
                      <img
                        src="{% static 'images/hapus.svg'%}"
                        height="100px"
                        width="100px"
                        alt="hapus"
                      /></div
                  ></a>
                </td>
              </tr>
              {% endfor %} {% else %}
              <tr>
                <td colspan="5">Data tidak ditemukan.</td>
              </tr>
              {% endif %}
            </tbody>
          </table>
        <div class="klik">
          <a href="{% url 'monyet:create'  %}" class="btn btn-success">New+</a>
        </div>
      </div>
    </div>
  </body>
</html>

kingkong/monyet/templates/hawkish/say.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Kingkong</title>
  </head>
  <body>
<div class="rumput">
  <div class="container">
      <h1>Detail Task</h1>

      <div>
        <a href="{% url 'monyet:index' %}" class="btn btn-success">Kembali ke Daftar</a>
      </div>

      <br>

      <div>
        <h2>{{ task.nama }}</h2>
        
        <h4><span class="badge badge-warning">{{ task.keluarga }}</span></h3>

        <p>
            {{ task.keluarga }}
        </p>
      </div>
  </div>
</div>
 
  </body>
</html>